import { useState } from "react";
import { X, AlertTriangle } from "lucide-react";
import { useAudit } from "../../audit/hooks/useAudit";
import type { GitHubSecurityAlert } from "../types/github.types";
import type { FindingRiskLevel } from "../../audit/types/audit.types";

interface Props {
  isOpen: boolean;
  onClose: () => void;
  alert: GitHubSecurityAlert;
  onSuccess: (findingId: string) => void;
}

export function ConvertAlertToFindingModal({
  isOpen,
  onClose,
  alert,
  onSuccess,
}: Props) {
  const { programs, createFinding } = useAudit();
  const [selectedProgramId, setSelectedProgramId] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  if (!isOpen) return null;

  const activePrograms = programs.filter(
    (p) => p.status === "in_progress" || p.status === "draft",
  );

  const handleConvert = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedProgramId) return;

    setLoading(true);
    setError(null);
    try {
      const riskMap: Record<string, FindingRiskLevel> = {
        critical: "critical",
        high: "high",
        medium: "medium",
        low: "low",
      };

      const defaultTitle =
        alert.summary ??
        alert.package_name ??
        `GitHub Alert #${alert.github_alert_number ?? "unk"}`;

      let alertUrl = "";
      if (alert.repository?.full_name) {
        const repoPath = alert.repository.full_name;
        if (alert.alert_type === "dependabot") {
          alertUrl = `https://github.com/${repoPath}/security/dependabot/${alert.github_alert_number}`;
        } else if (alert.alert_type === "code_scanning") {
          alertUrl = `https://github.com/${repoPath}/security/code-scanning/${alert.github_alert_number}`;
        } else if (alert.alert_type === "secret_scanning") {
          alertUrl = `https://github.com/${repoPath}/security/secret-scanning/${alert.github_alert_number}`;
        }
      }

      const finding = await createFinding({
        program_id: selectedProgramId,
        title: `[GitHub SecOps] ${defaultTitle}`,
        description:
          alert.description ||
          `Autogenerated finding from GitHub Security Alert.\nPackage: ${alert.package_name || "N/A"}\nVuln Version: ${alert.vulnerable_version || "N/A"}\nPatched Version: ${alert.patched_version || "N/A"}`,
        risk_level: riskMap[alert.severity] || "medium",
        source_type: "github",
        source_url: alertUrl || undefined,
      });

      onSuccess(finding.id);
    } catch (err: any) {
      setError(err.message || "Erro ao criar apontamento");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-background/80 backdrop-blur-sm">
      <div className="w-full max-w-md bg-background border border-border/50 rounded-2xl shadow-2xl overflow-hidden shadow-black/20">
        <div className="flex items-center justify-between p-4 border-b border-border/50">
          <h2 className="text-lg font-bold">Criar Apontamento</h2>
          <button
            onClick={onClose}
            className="p-2 rounded-xl hover:bg-muted text-muted-foreground transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleConvert} className="p-4 space-y-4">
          <div className="p-3 bg-primary/10 text-primary text-sm rounded-xl border border-primary/20 flex gap-3">
            <AlertTriangle className="w-5 h-5 shrink-0" />
            <div>
              <p className="font-bold">Alerta de Segurança</p>
              <p className="text-muted-foreground mt-0.5 line-clamp-1">
                {alert.summary ?? alert.package_name}
              </p>
            </div>
          </div>

          {error && (
            <div className="p-3 bg-red-500/10 text-red-500 text-sm rounded-xl border border-red-500/20">
              {error}
            </div>
          )}

          <div className="space-y-2">
            <label className="text-sm font-bold text-muted-foreground">
              Programa de Auditoria
            </label>
            <select
              required
              value={selectedProgramId}
              onChange={(e) => setSelectedProgramId(e.target.value)}
              className="w-full px-3 py-2 bg-background border border-border rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/50"
            >
              <option value="">Selecione um programa...</option>
              {activePrograms.map((p) => (
                <option key={p.id} value={p.id}>
                  {p.name} ({p.framework?.name || "Sem Framework"})
                </option>
              ))}
            </select>
          </div>

          <div className="flex justify-end gap-3 pt-4">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-sm font-bold text-muted-foreground hover:bg-muted rounded-xl transition-colors"
            >
              Cancelar
            </button>
            <button
              type="submit"
              disabled={loading || !selectedProgramId}
              className="px-4 py-2 text-sm font-bold text-primary-foreground bg-primary rounded-xl hover:bg-primary/90 transition-all disabled:opacity-50"
            >
              {loading ? "Criando..." : "Criar Apontamento"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
